In [1]:
import numpy as np

In [2]:
# binary classification
y_true = [1, 0, 0, 1, 1]
y_pred = [1, 0, 0, 0, 1]

y_test_a_lst = y_true
y_pred_a_lst = y_pred

y_test_a_arr = np.array(y_true)
y_pred_a_arr = np.array(y_pred)

print(y_test_a_lst, y_pred_a_lst)
print(y_test_a_arr, y_pred_a_arr)

[1, 0, 0, 1, 1] [1, 0, 0, 0, 1]
[1 0 0 1 1] [1 0 0 0 1]


In [3]:
# multi class classification
y_true = [0, 1, 2, 1, 2]
y_pred = [[0.9, 0.1, 0.0], [0.3, 0.2, 0.5], [0.2, 0.3, 0.5], [0.1, 0.8, 0.1], [0.1, 0.2, 0.7]]

y_test_b_lst = y_true
y_pred_b_lst = y_pred

y_test_b_arr = np.array(y_true)
y_pred_b_arr = np.array(y_pred)

print(y_test_b_lst, y_pred_b_lst)
print(y_test_b_arr, y_pred_b_arr)

[0, 1, 2, 1, 2] [[0.9, 0.1, 0.0], [0.3, 0.2, 0.5], [0.2, 0.3, 0.5], [0.1, 0.8, 0.1], [0.1, 0.2, 0.7]]
[0 1 2 1 2] [[0.9 0.1 0. ]
 [0.3 0.2 0.5]
 [0.2 0.3 0.5]
 [0.1 0.8 0.1]
 [0.1 0.2 0.7]]


In [7]:
# multi label classification
y_test = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
y_pred = [[0, 1, 2], [3, 4, 5], [6, 7, 9]]

y_test_c_lst = y_test
y_pred_c_lst = y_pred

y_test_c_arr = np.array(y_true)
y_pred_c_arr = np.array(y_pred)

print(y_test_c_lst, y_pred_c_lst)
print(y_test_c_arr, y_pred_c_arr)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]] [[0, 1, 2], [3, 4, 5], [6, 7, 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]
 [3 4 5]
 [6 7 9]]


In [11]:
!pip show -f ai-management

Name: ai-management
Version: 1.0.5
Summary: This is a toolbox to help AI & ML teams to have a better management of their metrics.
Home-page: https://github.com/adeo/aim
Author: Leroy Merlin Brazil
Author-email: chapter_inteligencia_artificia@leroymerlin.com.br
License: MIT
Location: c:\programdata\anaconda3\lib\site-packages
Requires: scikit-learn, pandas, google-cloud, numpy
Required-by: 
Files:
  __init__.py
  __pycache__\__init__.cpython-39.pyc
  __pycache__\constants.cpython-39.pyc
  __pycache__\main.cpython-39.pyc
  ai_management-1.0.5.dist-info\INSTALLER
  ai_management-1.0.5.dist-info\LICENSE.txt
  ai_management-1.0.5.dist-info\METADATA
  ai_management-1.0.5.dist-info\RECORD
  ai_management-1.0.5.dist-info\REQUESTED
  ai_management-1.0.5.dist-info\WHEEL
  ai_management-1.0.5.dist-info\top_level.txt
  constants.py
  main.py


In [8]:
import ai_management as aim
me = aim.ModelEvaluation()

ModuleNotFoundError: No module named 'ai_management'

In [5]:
# list test
me.historize_model_evaluation(
    soltn_nm = 'Solution X', 
    lst_mdls = [
        {
            'mdl_nm' : 'Model A',
            'algrthm_typ' : 'binary_classification',
            'data' : [y_test_a_lst, y_pred_a_lst]}, 
        {
            'mdl_nm' : 'Model B',
            'algrthm_typ' : 'multi_class_classification',
            'data' : [y_test_b_lst, y_pred_b_lst]},
        {
            'mdl_nm' : 'Model C',
            'algrthm_typ' : 'multi_label_classification',
            'data' : [y_test_c_lst, y_pred_c_lst]},
    ], 
    env_typ='dev'
)

NameError: name 'y_test_c_lst' is not defined

In [16]:
# array test
me.historize_model_evaluation(
    soltn_nm = 'Solution X', 
    lst_mdls = [
        {
            'mdl_nm' : 'Model A',
            'algrthm_typ' : 'binary_classification',
            'data' : [y_test_a_arr, y_pred_a_arr]}, 
        {
            'mdl_nm' : 'Model B',
            'algrthm_typ' : 'multi_class_classification',
            'data' : [y_test_b_arr, y_pred_b_arr]},
        {
            'mdl_nm' : 'Model C',
            'algrthm_typ' : 'multi_label_classification',
            'data' : [y_test_c_arr, y_pred_c_arr]},
    ], 
    env_typ='dev'
)

Wed Nov  8 14:25:03 2023, Start updating bi-dev-brlm.ods.FT_ARTFCL_INTLGNC_MDL_MTRC on mode 'WRITE_APPEND' 


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWar

SOLTN_NM   MDL_NM                 ALGRTHM_TYP     MDL_TYP  \
0   Solution X  Model A       binary_classification  supervised   
1   Solution X  Model A       binary_classification  supervised   
2   Solution X  Model A       binary_classification  supervised   
3   Solution X  Model A       binary_classification  supervised   
4   Solution X  Model A       binary_classification  supervised   
5   Solution X  Model A       binary_classification  supervised   
0   Solution X  Model B  multi_class_classification  supervised   
1   Solution X  Model B  multi_class_classification  supervised   
2   Solution X  Model B  multi_class_classification  supervised   
3   Solution X  Model B  multi_class_classification  supervised   
4   Solution X  Model B  multi_class_classification  supervised   
5   Solution X  Model B  multi_class_classification  supervised   
6   Solution X  Model B  multi_class_classification  supervised   
7   Solution X  Model B  multi_class_classification  supervised   
8   Solution X  Model B  multi_class_classification  supervised   
9   Solution X  Model B  multi_class_classification  supervised   
10  Solution X  Model B  multi_class_classification  supervised   
11  Solution X  Model B  multi_class_classification  supervised   
0   Solution X  Model C  multi_label_classification  supervised   
1   Solution X  Model C  multi_label_classification  supervised   
2   Solution X  Model C  multi_label_classification  supervised   
3   Solution X  Model C  multi_label_classification  supervised   
4   Solution X  Model C  multi_label_classification  supervised   
5   Solution X  Model C  multi_label_classification  supervised   
6   Solution X  Model C  multi_label_classification  supervised   
7   Solution X  Model C  multi_label_classification  supervised   
8   Solution X  Model C  multi_label_classification  supervised   

                  KPI_NM   KPI_QTY KPI_ARG                   TRNNG_TS  \
0               accuracy  0.800000    None 2023-11-08 14:25:03.578306   
1              precision  1.000000    None 2023-11-08 14:25:03.578306   
2                 recall  0.666667    None 2023-11-08 14:25:03.578306   
3                     f1  0.800000    None 2023-11-08 14:25:03.578306   
4                    auc  0.833333    None 2023-11-08 14:25:03.578306   
5                roc_auc  0.833333    None 2023-11-08 14:25:03.578306   
0               accuracy  0.800000    None 2023-11-08 14:25:03.592268   
1          roc_auc - ovo  0.916667    None 2023-11-08 14:25:03.592268   
2          roc_auc - ovr  0.888889    None 2023-11-08 14:25:03.592268   
3      precision - micro  0.800000    None 2023-11-08 14:25:03.592268   
4         recall - micro  0.800000    None 2023-11-08 14:25:03.592268   
5             f1 - micro  0.800000    None 2023-11-08 14:25:03.592268   
6      precision - macro  0.888889    None 2023-11-08 14:25:03.592268   
7         recall - macro  0.833333    None 2023-11-08 14:25:03.592268   
8             f1 - macro  0.822222    None 2023-11-08 14:25:03.592268   
9   precision - weighted  0.866667    None 2023-11-08 14:25:03.592268   
10     recall - weighted  0.800000    None 2023-11-08 14:25:03.592268   
11         f1 - weighted  0.786667    None 2023-11-08 14:25:03.592268   
0      precision - micro  0.888889    None 2023-11-08 14:25:03.618198   
1         recall - micro  0.888889    None 2023-11-08 14:25:03.618198   
2             f1 - micro  0.888889    None 2023-11-08 14:25:03.618198   
3      precision - macro  0.800000    None 2023-11-08 14:25:03.618198   
4         recall - macro  0.800000    None 2023-11-08 14:25:03.618198   
5             f1 - macro  0.800000    None 2023-11-08 14:25:03.618198   
6   precision - weighted  0.888889    None 2023-11-08 14:25:03.618198   
7      recall - weighted  0.888889    None 2023-11-08 14:25:03.618198   
8          f1 - weighted  0.888889    None 2023-11-08 14:25:03.618198   

                   TEC_CRE_DT                 TEC_UPT_DT    TEC_USER_UPT  
0  2023-1

DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.